# # Assignment 5
    V.VENU GOPAL REDDY
    Referral Code: DIRSS2115

### Q1.numpy stands for.?
    A)numpy stands for numerical python

### Q2.The most important object defined in Numpy is an N-dimensional array type called?
    A)ndarray

### Q3.what is the output of the following code.?


In [59]:
import numpy as np
a = np.array([1, 2, 3], dtype =complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [60]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [61]:
a = np.array([1, 2, 3], dtype ="float")
print (a)

[1. 2. 3.]


In [62]:
a = np.dtype('i4')
print (a)

int32


In [63]:
a = np.array([1, 2, 3,4,5], ndmin= 2)
print(a)

[[1 2 3 4 5]]


In [64]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)],
dtype = dt)
print( a['age'])

[10 20 30]


In [65]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a
print (c[2])

21


In [66]:
a = np.array([1,2,3,5,8])
a = a + 1
print (a[1])

3


In [67]:
a = np.array([[1,2,3],[0,1,4]])
print (a.size)

6


In [68]:
a = np.array([1,2,3,5,8])
print (a.ndim)
print (a.shape)
print (a.shape)
print()

1
(5,)
(5,)



In [69]:
a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
d

array([[2, 3, 4],
       [1, 2, 5]])

In [70]:
print (d[1,2])
print (d.size)
print (b)

5
6
[[0 0 0]
 [0 0 0]]


### Q4.You have a matrix defined as below:
    A = np.array([[6, 1, 1],
                [4, -2, 5],
                [2, 8, 7]])
      Find its -trace, rank, determinant, 
      inverse, transpose.

In [78]:
A = np.array([[6, 1, 1],[4, -2, 5],[2, 8, 7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

### Trace
The trace is the sum of diagonal elements in a square matrix. There are two methods to calculate the trace. We can simply use the trace() method of an ndarray object or get the diagonal elements first and then get the sum

In [72]:
print('Trace: ',A.trace())
print('Trace ',sum(A.diagonal()))

Trace:  11
Trace  11


### Rank
The rank of a matrix is the dimensions of the vector space spanned (generated) by its columns or rows. In other words, it can be defined as the maximum number of linearly independent column vectors or row vectors.

In [73]:
rank = np.linalg.matrix_rank(A)  #linalg ==  Linear Algebra
rank 

3

### Determinant
The determinant of a square matrix can be calculated det() function which also comes from the numpy linalg package. If the determinant is 0, that matrix is not invertible. It is known as a singular matrix in algebra terms.

In [85]:
det=np.linalg.det(A)



### Inverse
The true inverse of a square matrix can be found using the inv() function of the numpy linalg package. If the determinant of a square matrix is not 0, it has a true inverse.

In [94]:
inv = np.linalg.inv(A)
inv

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

### Eigenvalues and Eigenvectors
    The sum of eigenvalues (1+5+1=7) is equal to the trace (2+3+2=7) of the same matrix! The product of the eigenvalues (1x5x1=5) is equal to the determinant (5) of the same matrix!

In [89]:
w, v = np.linalg.eig(A)
w,v

(array([11.24862343,  5.09285054, -5.34147398]),
 array([[ 0.24511338,  0.75669314,  0.02645665],
        [ 0.40622202, -0.03352363, -0.84078293],
        [ 0.88028581, -0.65291014,  0.54072554]]))

### Transpose
    Transpose can be determined using 2 ways. Both ways are showed below.

In [90]:
print('Transpose',A.T)
print('Transpose',A.transpose())

Transpose [[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]
Transpose [[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


### Q5.

    list1 = [1, 2, 3, 4 ,5, 6]
    list2 = [10, 9, 8, 7, 6, 5]

In [113]:
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]
list3=list1+list2

In [114]:
list3

[1, 2, 3, 4, 5, 6, 10, 9, 8, 7, 6, 5]

### Q6.Type these lines of code and check.?
    the output for each of them.

In [35]:
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]

In [36]:
a=np.array([list1])
b=np.array([list2])

In [37]:
a*b

array([[10, 18, 24, 28, 30, 30]])

In [38]:
a^b

array([[11, 11, 11,  3,  3,  3]], dtype=int32)

In [39]:
a-b

array([[-9, -7, -5, -3, -1,  1]])

In [40]:
a+b

array([[11, 11, 11, 11, 11, 11]])

In [41]:
a/b

array([[0.1       , 0.22222222, 0.375     , 0.57142857, 0.83333333,
        1.2       ]])

In [42]:
a//b

array([[0, 0, 0, 0, 0, 1]], dtype=int32)